

Map<String, dynamic> createTripSchema() {
  return {
    'trip_id': "", //generated by app instance code
    'after_pic_url': "", //url in firebase storage
    'before_pic_url': "", //url in firebase storage
    'cents_price': 0,
    'end_time': DateTime, //time format
    'start_time': DateTime, //time format
    'rounded_up_mins_duration': 0,

    // Add more key-value pairs as needed
  };
}
Map<String, dynamic> updateTripSchema() {
  return {
    'after_pic_url': '', //url in firebase storage
    'cents_price': 1,
    'end_time': DateTime, //time format
    'rounded_up_mins_duration': 0,
  };
}