// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-pXhcGF8zaLAEijK4Dksmlfnx4t8Lkg',
    appId: '1:347731564601:web:07d64679f9475184aa95e8',
    messagingSenderId: '347731564601',
    projectId: 'blue-scooters',
    authDomain: 'blue-scooters.firebaseapp.com',
    storageBucket: 'blue-scooters.appspot.com',
    measurementId: 'G-22XQ3RJBFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvoSYrVwQvznQu9RM-BbM86KReDi_NEE',
    appId: '1:347731564601:android:c3ee24d81166fe54aa95e8',
    messagingSenderId: '347731564601',
    projectId: 'blue-scooters',
    storageBucket: 'blue-scooters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPMOeZYx7ysiPJEYvsEkH_996PIdEIWM',
    appId: '1:347731564601:ios:0705890ecf1a8c6caa95e8',
    messagingSenderId: '347731564601',
    projectId: 'blue-scooters',
    storageBucket: 'blue-scooters.appspot.com',
    iosBundleId: 'co.labib.bluescooters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPMOeZYx7ysiPJEYvsEkH_996PIdEIWM',
    appId: '1:347731564601:ios:11527f0a032281bfaa95e8',
    messagingSenderId: '347731564601',
    projectId: 'blue-scooters',
    storageBucket: 'blue-scooters.appspot.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
